# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AABYiDAA_4f7ruBY1-N9aWnJCcz5EH-PzBDmJyOa0";
    path = fetchzip {
      url = "https://github.com/natecraddock/lua/archive/refs/tags/5.1.5-1.tar.gz";
      hash = "sha256-/dh0sAmiHH/lP6aQq3MYXeHntwXONKPqeV9k4hhsVso=";
    };
  }
  {
    name = "N-V-__8AACcgQgCuLYTPzCp6pnBmFJHyG77RAtM13hjOfTaG";
    path = fetchzip {
      url = "https://github.com/LuaJIT/LuaJIT/archive/c525bcb9024510cad9e170e12b6209aedb330f83.tar.gz";
      hash = "sha256-2C6SrzOfIaymVwXggxc0qt/O+KRRQ9JLnn23cipchdo=";
    };
  }
  {
    name = "N-V-__8AAFB1kwDHb7dLmDsOv91rOkqorfDB_2nJtqnp4F-b";
    path = fetchzip {
      url = "https://github.com/luau-lang/luau/archive/refs/tags/0.653.tar.gz";
      hash = "sha256-29YBN4bA9SUkt63jeSs5Ta+sDr2vpDtagrDIj2zu7Ys=";
    };
  }
  {
    name = "N-V-__8AAIMvFABt-Qcpk24RD10ldEN743D8Q2e19Er8x3dJ";
    path = fetchzip {
      url = "https://www.lua.org/ftp/lua-5.4.7.tar.gz";
      hash = "sha256-o1jnQCcnlk2OXU4Cc8X7bJiOU2QN92vd91TtBhNM/hU=";
    };
  }
  {
    name = "N-V-__8AALg2DgDVsrOXOPBkTZ7Vt0MZc_Gha5N--G1M-FiH";
    path = fetchzip {
      url = "https://www.lua.org/ftp/lua-5.2.4.tar.gz";
      hash = "sha256-+GzRn/t1VyFTwGiKsZYkWynPK5ypCpzKBOYavsqWEc8=";
    };
  }
  {
    name = "N-V-__8AALihEACTeiI1Me9rP-qPZT3BNTELDoSAXn76FIhw";
    path = fetchzip {
      url = "https://www.lua.org/ftp/lua-5.3.6.tar.gz";
      hash = "sha256-ugEt/2zqY8c4+5W9CbUvfZq0S6FBR3BxtG3bj+0m57Y=";
    };
  }
  {
    name = "lua_wrapper-0.1.0-OyMC27fOBAAU3E2ueB-EWGSgsuCFQZL83pT0nQJ1ufOI";
    path = fetchzip {
      url = "https://github.com/natecraddock/ziglua/archive/7bfb3c2b87220cdc89ef01cc99a200dad7a28e50.tar.gz";
      hash = "sha256-12SWJQpRXhmLINYhyg+IoinUS9BP3lngmdFKjlL2RIo=";
    };
  }
  {
    name = "wayland-0.4.0-dev-lQa1kjfIAQCmhhQu3xF0KH-94-TzeMXOqfnP0-Dg6Wyy";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/f3c5d503e540ada8cbcb056420de240af0c094f7.tar.gz";
      hash = "sha256-/SVqUlFVr4wLsCn6rHGOha1abUBZY9JvsbumVUubmYo=";
    };
  }
  {
    name = "xkbcommon-0.4.0-dev-VDqIe3a9AQDQa1H4Vh7__mVphznD-7tyNWdnjFgf-9fC";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/87e0910e12af79cbb74a37143c881abea32c96b7.tar.gz";
      hash = "sha256-JGmSV6jIL/WhrJRvWBItLHhfoy+qqhKcMlU4TIK06KA=";
    };
  }
  {
    name = "zgl-1.1.0-p_NpAH2rCQCau2UOYRdNu2eC-_T4CMWcgpqpv8REofLl";
    path = fetchzip {
      url = "https://github.com/ziglibs/zgl/archive/1c9a016169921040417590e5a0817ca4644dc986.tar.gz";
      hash = "sha256-2Me6Y3oFaeF/xdyPTmoXot+QmRJ+9hdSVni7AbP1ps4=";
    };
  }
]
