return {
	background_color = { 1, 1, 1, 0.4 },
	font = {
		color = { 1, 1, 1, 1 },
		highlight_color = { 1, 1, 0, 1 },
		size = 16,
		family = "Arial",
		style = "Normal",
		weight = "bold",
		variant = "Normal",
		gravity = "Auto",
		stretch = "Normal",
		offset = { 5, 5 },
	},
	grid = {
		color = { 1, 1, 1, 1 },
		line_width = 2,
		size = { 80, 80 },
		offset = { 0, 0 },
		selected_color = { 1, 0, 0, 1 },
		selected_line_width = 2,
	},
	keys = {
		search = "asdfghjkl",
		bindings = {
			z = { move = { -5, 0 } },
			x = { move = { 0, 5 } },
			n = { move = { 0, -5 } },
			m = { move = { 5, 0 } },
			Z = { resize = { -5, 0 } },
			X = { resize = { 0, 5 } },
			N = { resize = { 0, -5 } },
			M = { resize = { 5, 0 } },
			H = { move_selection = { -5, 0 } },
			J = { move_selection = { 0, 5 } },
			K = { move_selection = { 0, -5 } },
			L = { move_selection = { 5, 0 } },
			c = "cancel_selection",
			[8] = "remove",
			q = "quit",
		},
	},
}
