return {
	background_color = "#7287FD66",
	font = {
		color = "#FFFFFF",
		highlight_color = "#DD7878",
		size = 16,
		family = "JetBrainsMono Nerd Font",
		style = "Normal",
		weight = 1000,
		variant = "Normal",
		gravity = "Auto",
		stretch = "Normal",
		offset = { 5, 5 },
	},
	grid = {
		color = "#C5A8EB",
		line_width = 2,
		size = { 80, 83 },
		offset = { 0, 0 },
		selected_color = "#40A02B",
		selected_line_width = 2,
	},
	keys = {
		search = "asdfghjkl",
		bindings = {
			z = { move = { -5, 0 } },
			x = { move = { 0, 5 } },
			n = { move = { 0, -5 } },
			m = { move = { 5, 0 } },
			Z = { resize = { -5, 0 } },
			X = { resize = { 0, 5 } },
			N = { resize = { 0, -5 } },
			M = { resize = { 5, 0 } },
			H = { move_selection = { -5, 0 } },
			J = { move_selection = { 0, 5 } },
			K = { move_selection = { 0, -5 } },
			L = { move_selection = { 5, 0 } },
			c = "cancel_selection",
			o = "border_select",
			[8] = "remove",
			q = "quit",
		},
	},
}
